version: "3"
services:
    database:
        container_name: database
        image: postgres:16.2-alpine3.19
        environment:
            POSTGRES_USER: iamtoolazytotip
            POSTGRES_PASSWORD: iamtoolazytotip
            POSTGRES_DB: tournaments
        shm_size: 256mb
        ports:
            - "5432:5432"
        networks:
            - simulator-network
        volumes:
            - type: bind
              source: ./database/migrate
              target: /docker-entrypoint-initdb.d/01_migrate
            - type: bind
              source: ./database/dev_setup
              target: /docker-entrypoint-initdb.d/02_dev_setup
            - type: bind
              source: ./database/initdb.sh
              target: /docker-entrypoint-initdb.d/initdb.sh

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U iamtoolazytotip -d tournaments"]
            interval: 3s
            timeout: 5s
            retries: 5

    # database-connection-test:
    #     container_name: database-connection-test
    #     image: postgres:16.2-alpine3.19
    #     command: psql postgresql://iamtoolazytotip:iamtoolazytotip@database/tournaments -c 'SELECT * FROM players;'
    #     working_dir: /app
    #     volumes:
    #         - type: bind
    #           source: ./database
    #           target: /app/
    #     networks:
    #         - simulator-network
    #     depends_on:
    #         database:
    #           condition: service_healthy

    api-server:
        container_name: go-api-server
        build:
            context: .
            dockerfile: ./docker/api.dockerfile
        image: iamtoolazytotip-api
        entrypoint: reflex -r '\.go$' -s -- sh -c "go run main.go"
        working_dir: /app
        networks:
            - simulator-network
        ports:
            - "8080:8080"
        volumes:
            - type: bind
              source: ./backend
              target: /app/

    frontend:
        container_name: frontend
        image: node:21.7.1-alpine3.18
        init: true
        command: /bin/sh -c "npm install && npm start"
        working_dir: /app
        networks:
            - simulator-network
        # ports:
        #     - "9000:9000"
        volumes:
            - type: bind
              source: ./frontend
              target: /app/

    nginx_local_dev_proxy:
        container_name: nginx-local-proxy
        init: true
        image: nginx:1.25.4
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./nginx/nginx.dev.conf
              target: /etc/nginx/nginx.conf
        command: [nginx-debug, '-g', 'daemon off;']
        networks:
            - simulator-network
        depends_on:
            frontend:
                condition: service_started
            api-server:
                condition: service_started

networks:
    simulator-network:
        driver: bridge
