version: "3"
services:
    api-server:
        container_name: go-api-server
        build:
            context: .
            dockerfile: ./docker/api.prod.dockerfile
        image: iamtoolazytotip-api-prod
        networks:
            - simulator-network
        # ports:
        #     - "8080:8080"

    nginx_local_dev_proxy:
        container_name: nginx-local-proxy
        init: true
        image: nginx:1.25.4
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
            - type: bind
              source: ./frontend/dist
              target: /usr/share/nginx/html
        command: [nginx-debug, '-g', 'daemon off;']
        networks:
            - simulator-network

networks:
    simulator-network:
        driver: bridge
