version: "3"
services:
    api-server:
        build:
            context: .
            dockerfile: ./docker/api.dockerfile
        image: iamtoolazytotip-api
        entrypoint: reflex -r '\.go$' -s -- sh -c "go run main.go"
        working_dir: /app
        networks:
            - simulator-network
        ports:
            - "8080:8080"
        volumes:
            - type: bind
              source: ./backend
              target: /app/

    frontend:
        image: node:21.7.1-alpine3.18
        init: true
        command: /bin/sh -c "npm install && npm start"
        working_dir: /app
        networks:
            - simulator-network
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./frontend
              target: /app/

networks:
    simulator-network:
        driver: bridge
