version: "3"
services:
    api-server:
        build:
            context: .
            dockerfile: ./docker/api.prod.dockerfile
        image: iamtoolazytotip-api-prod
        networks:
            - simulator-network
        ports:
            - "8080:8080"

    frontend:
        build:
            context: .
            dockerfile: ./docker/frontend.prod.dockerfile
        image: iamtoolazytotip-frontend
        init: true
        networks:
            - simulator-network
        ports:
            - "4173:4173"

networks:
    simulator-network:
        driver: bridge
