version: "3"
services:
    api:
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        image: iamtoolazytotip-api
        networks:
            - simulator-network
        ports:
            - "8080:8080"
    server:
        image: node:21.1-alpine3.17
        entrypoint: /bin/sh -c "npm install && npm start"
        working_dir: /app
        networks:
            - simulator-network
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./frontend
              target: /app/

networks:
    simulator-network:
        driver: bridge
