version: "3"
services:
    api:
        build:
            context: .
            dockerfile: ./docker/api.dockerfile
        image: iamtoolazytotip-api
        entrypoint: reflex -r '\.go$' -s -- sh -c "go run main.go"
        working_dir: /app
        networks:
            - simulator-network
        ports:
            - "8080:8080"
        volumes:
            - type: bind
              source: ./backend
              target: /app/

    server:
        image: node:21.1-alpine3.17
        entrypoint: /bin/sh -c "npm install && npm start"
        working_dir: /app
        networks:
            - simulator-network
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./frontend
              target: /app/
        stop_grace_period: 1s

networks:
    simulator-network:
        driver: bridge
