describe('create new tournament', () => {
  it('enter page', () => {
    cy.visit('http://localhost:3000/new');
    cy.get('input')
    .type("Group A{enter}")
    .type("Group B{enter}")
    .type("Group C{enter}")
    .type("Group D{enter}")
    .type("Group E{enter}")
    .type("Group F{enter}")

    cy.get('[data-cy="Group A-0"]').type("Country A-0")
    cy.get('[data-cy="Group A-1"]').type("Country A-1")
    cy.get('[data-cy="Group A-2"]').type("Country A-2")
    cy.get('[data-cy="Group A-3"]').type("Country A-3")
    cy.get('[data-cy="Group B-0"]').type("Country B-0")
    cy.get('[data-cy="Group B-1"]').type("Country B-1")
    cy.get('[data-cy="Group B-2"]').type("Country B-2")
    cy.get('[data-cy="Group B-3"]').type("Country B-3")
    cy.get('[data-cy="Group C-0"]').type("Country C-0")
    cy.get('[data-cy="Group C-1"]').type("Country C-1")
    cy.get('[data-cy="Group C-2"]').type("Country C-2")
    cy.get('[data-cy="Group C-3"]').type("Country C-3")
    cy.get('[data-cy="Group D-0"]').type("Country D-0")
    cy.get('[data-cy="Group D-1"]').type("Country D-1")
    cy.get('[data-cy="Group D-2"]').type("Country D-2")
    cy.get('[data-cy="Group D-3"]').type("Country D-3")
    cy.get('[data-cy="Group E-0"]').type("Country E-0")
    cy.get('[data-cy="Group E-1"]').type("Country E-1")
    cy.get('[data-cy="Group E-2"]').type("Country E-2")
    cy.get('[data-cy="Group E-3"]').type("Country E-3")
    cy.get('[data-cy="Group F-0"]').type("Country F-0")
    cy.get('[data-cy="Group F-1"]').type("Country F-1")
    cy.get('[data-cy="Group F-2"]').type("Country F-2")
    cy.get('[data-cy="Group F-3"]').type("Country F-3")

    cy.get('[data-cy="manage-matches-button"]').click()

    cy.get('[name="Group\ A-1-1"]').select("Country A-0")
    cy.get('[name="Group\ A-1-2"]').select("Country A-1")
    cy.get('[name="Group\ A-2-1"]').select("Country A-2")
    cy.get('[name="Group\ A-2-2"]').select("Country A-3")
    cy.get('[name="Group\ A-3-1"]').select("Country A-0")
    cy.get('[name="Group\ A-3-2"]').select("Country A-2")
    cy.get('[name="Group\ A-4-1"]').select("Country A-1")
    cy.get('[name="Group\ A-4-2"]').select("Country A-3")
    cy.get('[name="Group\ A-5-1"]').select("Country A-0")
    cy.get('[name="Group\ A-5-2"]').select("Country A-3")
    cy.get('[name="Group\ A-6-1"]').select("Country A-1")
    cy.get('[name="Group\ A-6-2"]').select("Country A-2")

    cy.get('[name="Group\ B-1-1"]').select("Country B-0")
    cy.get('[name="Group\ B-1-2"]').select("Country B-1")
    cy.get('[name="Group\ B-2-1"]').select("Country B-2")
    cy.get('[name="Group\ B-2-2"]').select("Country B-3")
    cy.get('[name="Group\ B-3-1"]').select("Country B-0")
    cy.get('[name="Group\ B-3-2"]').select("Country B-2")
    cy.get('[name="Group\ B-4-1"]').select("Country B-1")
    cy.get('[name="Group\ B-4-2"]').select("Country B-3")
    cy.get('[name="Group\ B-5-1"]').select("Country B-0")
    cy.get('[name="Group\ B-5-2"]').select("Country B-3")
    cy.get('[name="Group\ B-6-1"]').select("Country B-1")
    cy.get('[name="Group\ B-6-2"]').select("Country B-2")

    cy.get('[name="Group\ C-1-1"]').select("Country C-0")
    cy.get('[name="Group\ C-1-2"]').select("Country C-1")
    cy.get('[name="Group\ C-2-1"]').select("Country C-2")
    cy.get('[name="Group\ C-2-2"]').select("Country C-3")
    cy.get('[name="Group\ C-3-1"]').select("Country C-0")
    cy.get('[name="Group\ C-3-2"]').select("Country C-2")
    cy.get('[name="Group\ C-4-1"]').select("Country C-1")
    cy.get('[name="Group\ C-4-2"]').select("Country C-3")
    cy.get('[name="Group\ C-5-1"]').select("Country C-0")
    cy.get('[name="Group\ C-5-2"]').select("Country C-3")
    cy.get('[name="Group\ C-6-1"]').select("Country C-1")
    cy.get('[name="Group\ C-6-2"]').select("Country C-2")

    cy.get('[name="Group\ D-1-1"]').select("Country D-0")
    cy.get('[name="Group\ D-1-2"]').select("Country D-1")
    cy.get('[name="Group\ D-2-1"]').select("Country D-2")
    cy.get('[name="Group\ D-2-2"]').select("Country D-3")
    cy.get('[name="Group\ D-3-1"]').select("Country D-0")
    cy.get('[name="Group\ D-3-2"]').select("Country D-2")
    cy.get('[name="Group\ D-4-1"]').select("Country D-1")
    cy.get('[name="Group\ D-4-2"]').select("Country D-3")
    cy.get('[name="Group\ D-5-1"]').select("Country D-0")
    cy.get('[name="Group\ D-5-2"]').select("Country D-3")
    cy.get('[name="Group\ D-6-1"]').select("Country D-1")
    cy.get('[name="Group\ D-6-2"]').select("Country D-2")

    cy.get('[name="Group\ E-1-1"]').select("Country E-0")
    cy.get('[name="Group\ E-1-2"]').select("Country E-1")
    cy.get('[name="Group\ E-2-1"]').select("Country E-2")
    cy.get('[name="Group\ E-2-2"]').select("Country E-3")
    cy.get('[name="Group\ E-3-1"]').select("Country E-0")
    cy.get('[name="Group\ E-3-2"]').select("Country E-2")
    cy.get('[name="Group\ E-4-1"]').select("Country E-1")
    cy.get('[name="Group\ E-4-2"]').select("Country E-3")
    cy.get('[name="Group\ E-5-1"]').select("Country E-0")
    cy.get('[name="Group\ E-5-2"]').select("Country E-3")
    cy.get('[name="Group\ E-6-1"]').select("Country E-1")
    cy.get('[name="Group\ E-6-2"]').select("Country E-2")

    cy.get('[name="Group\ F-1-1"]').select("Country F-0")
    cy.get('[name="Group\ F-1-2"]').select("Country F-1")
    cy.get('[name="Group\ F-2-1"]').select("Country F-2")
    cy.get('[name="Group\ F-2-2"]').select("Country F-3")
    cy.get('[name="Group\ F-3-1"]').select("Country F-0")
    cy.get('[name="Group\ F-3-2"]').select("Country F-2")
    cy.get('[name="Group\ F-4-1"]').select("Country F-1")
    cy.get('[name="Group\ F-4-2"]').select("Country F-3")
    cy.get('[name="Group\ F-5-1"]').select("Country F-0")
    cy.get('[name="Group\ F-5-2"]').select("Country F-3")
    cy.get('[name="Group\ F-6-1"]').select("Country F-1")
    cy.get('[name="Group\ F-6-2"]').select("Country F-2")
    cy.pause()
  })

})
