name: Build cloud images
run-name: ${{ github.actor }} runs unittests for the simulator backend 🚀
on:
    workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug
          tags:
            description: 'Test scenario tags'
            required: false
            type: boolean
          environment:
            description: 'Environment to run tests against'
            type: environment
            required: true
jobs:
    simulator-build-cloud-image:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Log level: $LEVEL"
                echo "Tags: $TAGS"
                echo "Environment: $ENVIRONMENT"
              env:
                LEVEL: ${{ inputs.logLevel }}
                TAGS: ${{ inputs.tags }}
                ENVIRONMENT: ${{ inputs.environment }}
